In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
import itertools
#from google.colab import files

In [2]:
#uploaded = files.upload()

Saving train_upd.csv to train_upd (1).csv


In [4]:
train = pd.read_csv("train_upd.csv", engine='python', skipfooter=1)
train.head()

cell_name  4G_rat  par_year  par_month  par_day  par_hour  par_min  \
0  1090595862       1      2018         12       15         0       50   
1  4826375369       1      2018         12        7        20        5   
2  3607540856       1      2018         12        5        16       35   
3  1245076813       0      2018         12       16        21       60   
4   404129745       1      2018         12        4         6       60   

   subscriber_count  web_browsing_total_bytes  video_total_bytes  \
0               152                       315              59012   
1                54                      1871                334   
2               277                       887                945   
3                51                      8577                494   
4               117                      2084               1056   

        ...         email_total_bytes  weather_total_bytes  media_total_bytes  \
0       ...                        10                   33                 46   
1       ...                        22                   20                  7   
2       ...                        14                   91                 49   
3       ...                        10                   63                 42   
4       ...                        67                   59                 91   

   mms_total_bytes  others_total_bytes  beam_direction  cell_range  tilt  \
0               39                 103              69           6     2   
1               10                  21              93           7     5   
2              147                 159              77           6     3   
3               75                  35              95           7     2   
4              197                 316             112           3     5   

   ran_vendor  Congestion_Type  
0    ERICSSON                2  
1       NOKIA                0  
2    ERICSSON                1  
3      HUAWEI                1  
4      HUAWEI                3  

[5 rows x 39 columns]

In [10]:
train.isnull().sum()

cell_name                        0
4G_rat                           0
par_year                         0
par_month                        0
par_day                          0
par_hour                         0
par_min                          0
subscriber_count                 0
web_browsing_total_bytes         0
video_total_bytes                0
social_ntwrking_bytes            0
cloud_computing_total_bytes      0
web_security_total_bytes         0
gaming_total_bytes               0
health_total_bytes               0
communication_total_bytes        0
file_sharing_total_bytes         0
remote_access_total_bytes        0
photo_sharing_total_bytes        0
software_dwnld_total_bytes       0
marketplace_total_bytes          0
storage_services_total_bytes     0
audio_total_bytes                0
location_services_total_bytes    0
prese0e_total_bytes              0
advertisement_total_bytes        0
system_total_bytes               0
voip_total_bytes                 0
speedtest_total_byte

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78559 entries, 0 to 78558
Data columns (total 39 columns):
cell_name                        78559 non-null int64
4G_rat                           78559 non-null int64
par_year                         78559 non-null int64
par_month                        78559 non-null int64
par_day                          78559 non-null int64
par_hour                         78559 non-null int64
par_min                          78559 non-null int64
subscriber_count                 78559 non-null int64
web_browsing_total_bytes         78559 non-null int64
video_total_bytes                78559 non-null int64
social_ntwrking_bytes            78559 non-null int64
cloud_computing_total_bytes      78559 non-null int64
web_security_total_bytes         78559 non-null int64
gaming_total_bytes               78559 non-null int64
health_total_bytes               78559 non-null int64
communication_total_bytes        78559 non-null int64
file_sharing_total_bytes   

In [12]:
uploaded2= files.upload()

Saving test_upd.csv to test_upd.csv


In [13]:
print('The number of samples into the train data is {}.'.format(train.shape[0]))

The number of samples into the train data is 78559.


In [0]:
test =pd.read_csv("test_upd.csv", engine='python', skipfooter=1)

In [17]:
print('The number of samples into the test data is {}.'.format(test.shape[0]))

The number of samples into the test data is 26304.


In [18]:
print(test.shape)

(26304, 38)


In [19]:
print(train.shape)

(78559, 39)


In [0]:
train.drop('par_year', axis=1, inplace=True)
train.drop('par_month', axis=1, inplace=True)
train.drop('cell_name', axis=1, inplace=True)

In [0]:
test.drop('par_year', axis=1, inplace=True)
test.drop('par_month', axis=1, inplace=True)
test.drop('cell_name', axis=1, inplace=True)

In [22]:
print(train.shape)
print(test.shape)

(78559, 36)
(26304, 35)


In [0]:
xx_train = train.iloc[:, 35]
yy_train = train.iloc[:, :-1]

In [0]:
y_train = train.iloc[:, 35]
X_train = train.iloc[:, :-1].values

In [25]:
X_train

array([[1, 15, 0, ..., 6, 2, 'ERICSSON'],
       [1, 7, 20, ..., 7, 5, 'NOKIA'],
       [1, 5, 16, ..., 6, 3, 'ERICSSON'],
       ...,
       [0, 2, 8, ..., 5, 5, 'HUAWEI'],
       [1, 6, 1, ..., 4, 4, 'ERICSSON'],
       [1, 7, 21, ..., 5, 5, 'ERICSSON']], dtype=object)

In [26]:
y_train

0        2
1        0
2        1
3        1
4        3
5        3
6        2
7        0
8        3
9        2
10       0
11       2
12       2
13       3
14       3
15       0
16       1
17       2
18       0
19       1
20       2
21       3
22       1
23       0
24       3
25       0
26       0
27       1
28       3
29       3
        ..
78529    1
78530    0
78531    3
78532    3
78533    0
78534    1
78535    0
78536    2
78537    0
78538    3
78539    2
78540    0
78541    1
78542    2
78543    1
78544    0
78545    1
78546    2
78547    0
78548    2
78549    0
78550    2
78551    0
78552    2
78553    3
78554    2
78555    2
78556    2
78557    2
78558    1
Name: Congestion_Type, Length: 78559, dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

labelencoder_X = LabelEncoder()
X_train[:, 34] = labelencoder_X.fit_transform(X_train[:, 34])

onehotencoder = OneHotEncoder(categorical_features = [34],sparse=False)
X_train = onehotencoder.fit_transform(X_train)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [28]:
print(X_train)

[[  1.   0.   0. ...  69.   6.   2.]
 [  0.   0.   1. ...  93.   7.   5.]
 [  1.   0.   0. ...  77.   6.   3.]
 ...
 [  0.   1.   0. ... 117.   5.   5.]
 [  1.   0.   0. ...  95.   4.   4.]
 [  1.   0.   0. ...  73.   5.   5.]]


In [29]:
X_train.shape

(78559, 37)

In [0]:
X_test = test.iloc[:, :35].values

In [31]:
X_test.shape

(26304, 35)

In [0]:
X_test = test.iloc[:, :35].values

In [33]:
print(X_test)

[[1 8 23 ... 3 3 'ERICSSON']
 [1 20 5 ... 6 3 'HUAWEI']
 [1 15 13 ... 4 5 'HUAWEI']
 ...
 [0 3 3 ... 4 2 'HUAWEI']
 [1 18 11 ... 2 3 'HUAWEI']
 [0 2 21 ... 4 5 'HUAWEI']]


In [34]:
X_test[:,34]

array(['ERICSSON', 'HUAWEI', 'HUAWEI', ..., 'HUAWEI', 'HUAWEI', 'HUAWEI'],
      dtype=object)

In [35]:

labelencoder_X = LabelEncoder()
X_test[:, 34] = labelencoder_X.fit_transform(X_test[:, 34])


onehotencoder = OneHotEncoder(categorical_features = [34],sparse=False)
X_test = onehotencoder.fit_transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [36]:
print(X_test)
print(X_test.shape)

[[  1.   0.   0. ... 120.   3.   3.]
 [  0.   1.   0. ...  91.   6.   3.]
 [  0.   1.   0. ...  63.   4.   5.]
 ...
 [  0.   1.   0. ...  94.   4.   2.]
 [  0.   1.   0. ...  99.   2.   3.]
 [  0.   1.   0. ...  62.   4.   5.]]
(26304, 37)


In [0]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

labelencoder_y = LabelEncoder()
y_train = labelencoder_y.fit_transform(y_train)

In [38]:
print(y_train)

[2 0 1 ... 2 2 1]


In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)

In [0]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_train, y_train, test_size=0.25)

In [0]:
from sklearn.metrics import matthews_corrcoef

In [42]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree
clf1 = BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
clf1.fit(X_train1, y_train1)
y_pred = clf1.predict(X_test1)
print(clf1.score(X_test1,y_test1))
#print(matthews_corrcoef(y_test1, y_pred)) 

KeyboardInterrupt: ignored

In [0]:
from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier(random_state=1)
clf2.fit(X_train1, y_train1)
y_pred = clf2.predict(X_test1)
print(clf2.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [43]:
from sklearn.ensemble import AdaBoostClassifier
clf3 = AdaBoostClassifier(random_state=1)

clf3.fit(X_train1, y_train1)
y_pred = clf3.predict(X_test1)
print(clf3.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.7227596741344195
0.6307494919055099


In [0]:
from sklearn.ensemble import GradientBoostingClassifier
clf4 = GradientBoostingClassifier(learning_rate=0.01,random_state=1)
clf4.fit(X_train1, y_train1)
y_pred = clf4.predict(X_test1)
print(clf4.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [0]:
import xgboost as xgb
clf5 =xgb.XGBClassifier(random_state=1,learning_rate=0.01)
clf5.fit(X_train1, y_train1)
y_pred = clf5.predict(X_test1)
print(clf5.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [44]:
from sklearn.naive_bayes import GaussianNB
clf6 = GaussianNB()
clf6.fit(X_train1, y_train1)
y_pred = clf6.predict(X_test1)
print(clf6.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.7426680244399185
0.6575904583383891


In [0]:
from sklearn.tree import DecisionTreeClassifier
clf7 = DecisionTreeClassifier(criterion='entropy',random_state=0)
clf7.fit(X_train1, y_train1)
y_pred = clf7.predict(X_test1)
print(clf7.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [46]:
from sklearn.svm import SVC
clf8 = SVC(kernel='rbf',random_state=16)
clf8.fit(X_train1, y_train1)
y_pred = clf8.predict(X_test1)
print(clf8.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.7869653767820773
0.7162989125321597


In [45]:
from sklearn.svm import SVC
clf9 = SVC(kernel = 'linear',random_state=0)
clf9.fit(X_train1, y_train1)
y_pred = clf9.predict(X_test1)
print(clf9.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.7889511201629328
0.7188011570968349


In [47]:
from sklearn.neural_network import MLPClassifier
clf12 = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

clf12.fit(X_train1, y_train1)
y_pred = clf12.predict(X_test1)
print(clf12.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.790071283095723
0.7202444262433159


In [0]:
from sklearn.neural_network import MLPClassifier
clf13 = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
clf13.fit(X_train1, y_train1)
y_pred = clf13.predict(X_test1)
print(clf13.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [48]:
from sklearn.neural_network import MLPClassifier
clf14 = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(25, 2), random_state=1)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

clf14.fit(X_train1, y_train1)
y_pred = clf14.predict(X_test1)
print(clf14.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.7856924643584522
0.7145523717295105


In [0]:
from sklearn.neural_network import MLPClassifier
clf15 = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(100, 2), random_state=1)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

clf15.fit(X_train1, y_train1)
y_pred = clf15.predict(X_test1)

print(clf15.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [49]:
from sklearn.neural_network import MLPClassifier
clf16 = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False,
              epsilon=1e-08, hidden_layer_sizes=(5, 2),
              learning_rate='constant', learning_rate_init=0.0001,
              max_iter=200, momentum=0.9, n_iter_no_change=10,
              nesterovs_momentum=True, power_t=0.5, random_state=1,
              shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

clf16.fit(X_train1, y_train1)
y_pred = clf16.predict(X_test1)

print(clf16.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

0.7895112016293279
0.7194641861405457


In [0]:
from sklearn.linear_model import SGDClassifier
clf17 = SGDClassifier(loss="log", penalty="l1", max_iter=5)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
           early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
           l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=5,
           n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l1',
           power_t=0.5, random_state=None, shuffle=True, tol=None,
           validation_fraction=0.1, verbose=0, warm_start=False)

clf17.fit(X_train1, y_train1)
y_pred = clf17.predict(X_test1)

print(clf17.score(X_test1,y_test1))
print(matthews_corrcoef(y_test1, y_pred)) 

In [50]:
from sklearn.ensemble import VotingClassifier
estimators = [('AdaBoost', clf3), ('NB', clf6), ('SVC-rbf', clf8), ('SVC-linear', clf9), ('lbfgs-relu', clf12), ('Adam-relu', clf14), ('Adam-Tanh', clf16)]
eclf = VotingClassifier(estimators, voting='hard')
eclf.fit(X_train1, y_train1)
y_pred = eclf.predict(X_test1)
print(eclf.score(X_test1,y_test1))

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.7909368635437882


In [52]:
#uploaded3 = files.upload()
#w = pd.read_csv("test_upd.csv", engine='python', skipfooter=1)


Saving test_upd.csv to test_upd (1).csv


In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

X_test = sc_X.fit_transform(X_test)

In [0]:
w = pd.read_csv("test_upd.csv", engine='python', skipfooter=1)

In [0]:
y_prediction = eclf.predict(X_test)

In [0]:
Cell_Name = w['cell_name']
Final_Pred = pd.DataFrame({'cell_name':Cell_Name, 'Congestion_Type':y_prediction})
Final_Pred.to_csv('Predictions_n.csv')

In [0]:
Final_Pred['Congestion_Type'] = Final_Pred['Congestion_Type'].map({0:'NC', 1:'3G_BACKHAUL_CONGESTION', 2:'4G_BACKHAUL_CONGESTION', 3:'4G_RAN_CONGESTION'}).astype(str)

In [93]:
print(Final_Pred)

              Congestion_Type   cell_name
0      3G_BACKHAUL_CONGESTION  4398447675
1      3G_BACKHAUL_CONGESTION  4152570378
2           4G_RAN_CONGESTION  2902602672
3                          NC  1080083695
4      4G_BACKHAUL_CONGESTION  4413045057
5      3G_BACKHAUL_CONGESTION  2401138745
6           4G_RAN_CONGESTION   430135868
7      3G_BACKHAUL_CONGESTION  2602660266
8           4G_RAN_CONGESTION  1845742365
9           4G_RAN_CONGESTION   155531973
10                         NC  1460550754
11          4G_RAN_CONGESTION  2680109990
12          4G_RAN_CONGESTION  2008893435
13     4G_BACKHAUL_CONGESTION   267057221
14                         NC  3838788525
15                         NC  5045794024
16                         NC  5315600179
17                         NC  1103445815
18                         NC  2225965608
19     4G_BACKHAUL_CONGESTION  3204566964
20                         NC  2358057980
21                         NC  2015394225
22                         NC   26

In [0]:
#from google.colab import files
#files.download('Predictions_n.csv') 